version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - todo-net

    nginx:
        image: nginx:latest
        container_name: todo-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - todo-net

    db:
        image: mysql:8.0
        container_name: todo-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_app
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: password1
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - todo-net

volumes:
    db_data:

networks:
    todo-net:
        driver: bridge
